language: swift
cache:
  bundler: true
  cocoapods: true
osx_image: xcode11.3
before_install:
  - brew cask install adoptopenjdk/openjdk/adoptopenjdk8
  - brew cask install android-sdk
podfile: multiconfig-ios/Podfile
script:
  - ci_build/build.sh
deploy:
  provider: releases
  api_key: $GITHUB_OAUTH2_TOKEN
  file:
    - MultiConfig-Debug.zip
    - MultiConfigCommon-Debug.zip
    - MultiConfig-Release.zip
    - MultiConfigCommon-Release.zip
  skip_cleanup: true
  on:
    tags: true