language: swift
osx_image: xcode11.3
before_install:
  - brew cask install adoptopenjdk/openjdk/adoptopenjdk8
  - brew cask install android-sdk
podfile: multiconfig-ios/Podfile
script:
  - export JAVA_HOME=`/usr/libexec/java_home -v 1.8.0_252`
  - export ANDROID_SDK_ROOT="$(brew --prefix)/share/android-sdk"
  - /usr/libexec/java_home -V
  - echo $JAVA_HOME
  - java -version
  - yes |  /usr/local/share/android-sdk/tools/bin/sdkmanager --licenses
  - xcodebuild -sdk iphonesimulator13.2 -configuration Release -workspace multiconfig-ios/multiconfig-ios.xcworkspace -scheme multiconfig-ios build CODE_SIGNING_ALLOWED=NO
  - export BUILD_PRODUCT_DIR=$(xcodebuild -scheme multiconfig-ios -workspace multiconfig-ios/multiconfig-ios.xcworkspace ONLY_ACTIVE_ARCH=NO -sdk iphonesimulator13.2 -configuration Release -showBuildSettings | grep -m 1 "BUILT_PRODUCTS_DIR" | grep -oEi "\/.*")
  - (cd $BUILD_PRODUCT_DIR ; zip -r MultiConfig.zip ./MultiConfig.framework)
  - (cd $BUILD_PRODUCT_DIR ; zip -r MultiConfigCommon.zip ./MultiConfigCommon.framework)