# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'sampleios' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for sampleios
  pod 'MultiConfig', '~> 1.0.48'
end

target 'sampleios config' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for sampleios config
  pod 'MultiConfig', '~> 1.0.48'
end

target 'sampleios dev' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for sampleios dev
  pod 'MultiConfig', '~> 1.0.48'

end
