platform :ios, '13.0'
target 'multiconfig-ios' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for multiconfig-ios
  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'

end

target 'MultiConfigTests' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MultiConfigTests
  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'

end