name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: olegtarasov/get-tag@v2
        id: tagName
      - name: Run, Build & Deploy to Jfrog
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}
        run: |
          ./gradlew testReleaseUnitTest -b app/build.gradle
          ./gradlew install
          ./gradlew bintrayUpload