name: Deploy to Cocoapod Action
on:
  release:
    types: [published]
    tags:
      - '*'
jobs:
  build:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v1

      - name: Install Cocoapods
        run: gem install cocoapods

      - name: Deploy to Cocoapods
        run: |
          set -eo pipefail
          export LIB_VERSION=$(git describe --tags `git rev-list --tags --max-count=1`)
          pod spec lint MultiConfigCommon.podspec --allow-warnings
          pod trunk push MultiConfigCommon.podspec --allow-warnings
          pod spec lint MultiConfig.podspec --allow-warnings
          pod trunk push MultiConfig.podspec --allow-warnings

          pod spec lint MultiConfigCommon-Debug.podspec --allow-warnings
          pod trunk push MultiConfigCommon-Debug.podspec --allow-warnings
          pod spec lint MultiConfig-Debug.podspec --allow-warnings
          pod trunk push MultiConfig-Debug.podspec --allow-warnings
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
