- name: Deploy to Cocoapod Action
on:
  registry_package:
    types: [published]
    tags:
      - '*'
jobs:
  build:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v1

      - name: Install Cocoapods
        run: gem install cocoapods

      - name: Deploy to Cocoapods
        run: |
          set -eo pipefail
          export LIB_VERSION=$(git describe --tags `git rev-list --tags --max-count=1`)
          pod lib lint MultiConfigCommon.podspec --allow-warnings
          pod trunk push MultiConfigCommon.podspec --allow-warnings
          pod lib lint MultiConfig.podspec --allow-warnings
          pod trunk push MultiConfig.podspec --allow-warnings
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}